name: Docker Build

on:
  push:
    paths:
      - 'package.json'
      - 'packages/cli/**'

jobs:
  build-cli-docker-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: packages/cli/Dockerfile

