name: Docker Build

on:
  push:
    paths:
      - 'package.json'
      - 'packages/cli/**'
      - 'eslint.config.js'
      - '.github/workflows/cli-docker-build.yml'

// AI! Can you make the trivy scan run before pushing the image?
jobs:
  build-cli-docker-head:
    # Only run this job on pushes to main or master branch
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/cli/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ env.REPO }}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

