name: PNPM Recursive Build & Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm -r install
    - run: cd packages/browser && pnpm exec playwright install
    - run: pnpm lint
    - run: pnpm -r test

  test-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: 'pnpm'
    - run: pnpm -r install
    - run: cd packages/browser && pnpm exec playwright install ${{ matrix.browser }} && pnpm exec playwright install-deps ${{ matrix.browser }}
    - run: cd packages/browser && pnpm exec vitest --run --browser=${{ matrix.browser }}

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: 'pnpm'
    - run: pnpm -r install
    - name: Run Trivy vulnerability scanner for filesystem dependencies
      # Scans the entire filesystem, including pnpm-lock.yaml, for library vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'library'
        severity: 'CRITICAL,HIGH'

